/*
 * generated by Xtext
 */
package com.opcoach.dsgen.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDSGenDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.opcoach.com/dsgen/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.opcoach.generator/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.eclipse.org/emf/2002/Ecore"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.opcoach.com/dsgen/generator/1.0"));
		return result;
	}
}
