/*
* generated by Xtext
*/
package com.opcoach.dsgen.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DSGenDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.opcoach.dsgen.xtext.ui.internal.DSGenDSLActivator.getInstance().getInjector("com.opcoach.dsgen.xtext.DSGenDSL");
	}
	
}
