<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_n2OAwBQDEd-QiqGdp3e77Q" name="generator" nsURI="http://www.opcoach.generator/1.0"
    nsPrefix="gen">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_vHkHcBQDEd-QiqGdp3e77Q" name="ValueGenerator"
      abstract="true">
    <eTypeParameters xmi:id="_wGyv0BQDEd-QiqGdp3e77Q" name="T"/>
    <eOperations name="generateValue">
      <eGenericType eTypeParameter="#_wGyv0BQDEd-QiqGdp3e77Q"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badValueProportion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The badValueProportion is the percent of bad values to be generated.&#xA;This is an int that must be in [0,100] (out of bounds values will be considered as bounds)&#xA;If value is greater than 0, the badValueGenerator must be set."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="badValueGenerator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A optionnal bad value generator when a bad value should be generated. &#xA;It can ben a NullValueGenerator, or any other generator which could generate an out of bound value.&#xA;This generator must be set if the badValueProportion is defined (> 0)"/>
      </eAnnotations>
      <eGenericType eClassifier="#_vHkHcBQDEd-QiqGdp3e77Q">
        <eTypeArguments eTypeParameter="#_wGyv0BQDEd-QiqGdp3e77Q"/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastGeneratedValue" derived="true">
      <eGenericType eTypeParameter="#_wGyv0BQDEd-QiqGdp3e77Q"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomSeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"
        defaultValueLiteral="0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locale" eType="#//Locale"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeGenerator" abstract="true">
    <eTypeParameters name="T"/>
    <eOperations name="setBounds">
      <eParameters name="low">
        <eGenericType eTypeParameter="#//RangeGenerator/T"/>
      </eParameters>
      <eParameters name="high">
        <eGenericType eTypeParameter="#//RangeGenerator/T"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="low">
      <eGenericType eTypeParameter="#//RangeGenerator/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="high">
      <eGenericType eTypeParameter="#//RangeGenerator/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step">
      <eGenericType eTypeParameter="#//RangeGenerator/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#_vHkHcBQDEd-QiqGdp3e77Q">
      <eTypeArguments eTypeParameter="#//RangeGenerator/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceGenerator">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The step for choosing data in the values collection, when no random is required. Default value is 1."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" transient="true">
      <eGenericType eClassifier="#//Collection">
        <eTypeArguments eTypeParameter="#//ReferenceGenerator/T"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#_vHkHcBQDEd-QiqGdp3e77Q">
      <eTypeArguments eTypeParameter="#//ReferenceGenerator/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Collection" instanceClassName="java.util.Collection">
    <eTypeParameters name="T"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Locale" instanceClassName="java.util.Locale"/>
  <eSubpackages name="basic" nsURI="http://www.opcoach.com/generator/basic/1.0" nsPrefix="genbasic">
    <eClassifiers xsi:type="ecore:EClass" name="BooleanGenerator">
      <eGenericSuperTypes eClassifier="#_vHkHcBQDEd-QiqGdp3e77Q">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DateGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateNow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eGenericSuperTypes eClassifier="#//RangeGenerator">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DoubleGenerator">
      <eGenericSuperTypes eClassifier="#//RangeGenerator">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FloatGenerator">
      <eGenericSuperTypes eClassifier="#//RangeGenerator">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IDGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="10"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="#_vHkHcBQDEd-QiqGdp3e77Q">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntGenerator">
      <eGenericSuperTypes eClassifier="#//RangeGenerator">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LongGenerator">
      <eGenericSuperTypes eClassifier="#//RangeGenerator">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullValueGenerator">
      <eGenericSuperTypes eClassifier="#_vHkHcBQDEd-QiqGdp3e77Q">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="casePolicy" eType="#//basic/CasePolicyType"
          defaultValueLiteral="DEFAULT"/>
      <eGenericSuperTypes eClassifier="#//ReferenceGenerator">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CasePolicyType">
      <eLiterals name="DEFAULT"/>
      <eLiterals name="UPPERCASE" value="1"/>
      <eLiterals name="LOWERCASE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TrueGenerator" eSuperTypes="#//basic/BooleanGenerator"/>
    <eClassifiers xsi:type="ecore:EClass" name="FalseGenerator" eSuperTypes="#//basic/BooleanGenerator"/>
  </eSubpackages>
</ecore:EPackage>
