/*
* generated by Xtext
*/
package com.opcoach.datasample.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DataSampleDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/opcoach/datasample/xtext/parser/antlr/internal/InternalDataSampleDSL.tokens");
	}
}
