/*
 * generated by Xtext
 */
package com.opcoach.datasample.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DataSampleDSLRuntimeModule extends com.opcoach.datasample.xtext.AbstractDataSampleDSLRuntimeModule {

}
