/*
* generated by Xtext
*/
package com.opcoach.datasample.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DataSampleDSLStandaloneSetup extends DataSampleDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new DataSampleDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

