/*
 * generated by Xtext
 */
package com.opcoach.dsgen.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DSGenDSLUiModule extends com.opcoach.dsgen.xtext.ui.AbstractDSGenDSLUiModule {
	public DSGenDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
