/*
 * generated by Xtext
 */
package com.opcoach.dsgen.xtext.ui.contentassist

import com.opcoach.dsgen.xtext.ui.contentassist.AbstractDSGenDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DSGenDSLProposalProvider extends AbstractDSGenDSLProposalProvider {
}
