<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dsgen" nsURI="http://www.opcoach.com/dsgen/1.0" nsPrefix="dsgen">
  <eClassifiers xsi:type="ecore:EClass" name="DSGenModel" eSuperTypes="#//DSGenBase">
    <eOperations name="getRoot" eType="#//DSGenClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsgenPackages" upperBound="-1"
        eType="#//DSGenPackage" containment="true" eOpposite="#//DSGenPackage/dsgenModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomSeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenPackage" eSuperTypes="#//DSGenBase">
    <eAnnotations source="dsg.name">
      <details key="foo" value="bar"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecorePackage" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsgenModel" lowerBound="1"
        eType="#//DSGenModel" eOpposite="#//DSGenModel/dsgenPackages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsgenClassifiers" upperBound="-1"
        eType="#//DSGenClassifier" containment="true" eOpposite="#//DSGenClassifier/dsgenPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenClass" eSuperTypes="#//DSGenClassifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbAssociationRefTo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generator" eType="#//generator/EObjectGenerator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenFeature" eSuperTypes="#//DSGenTypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullableValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullablePercent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsgenClass" lowerBound="1"
        eType="#//DSGenClassifier" eOpposite="#//DSGenClassifier/dsgenFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreFeature" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generator" containment="true">
      <eGenericType eClassifier="ecore:EClass ../../com.opcoach.generator.model/model/generator.ecore#//ValueGenerator">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenBase" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenEnumLiteral" eSuperTypes="#//DSGenBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenClassifier" abstract="true" eSuperTypes="#//DSGenBase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreClass" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsgenFeatures" upperBound="-1"
        eType="#//DSGenFeature" containment="true" eOpposite="#//DSGenFeature/dsgenClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsgenPackage" lowerBound="1"
        eType="#//DSGenPackage" eOpposite="#//DSGenPackage/dsgenClassifiers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenDataType" eSuperTypes="#//DSGenClassifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenTypedElement" abstract="true" eSuperTypes="#//DSGenBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenAnnotation" eSuperTypes="#//DSGenBase"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenTypeParameter" eSuperTypes="#//DSGenBase"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DSGenRuntimeVersion"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DSGenJDKLevel"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DSGenDelegationKind"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DSGenPropertyKind"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DSGenResourceKind"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenAttribute" eSuperTypes="#//DSGenFeature"/>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenReference" eSuperTypes="#//DSGenFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDSGenClass" eType="#//DSGenClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSGenEnum" eSuperTypes="#//DSGenDataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreEnum" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EEnum"/>
  </eClassifiers>
  <eSubpackages name="generator" nsURI="http://www.opcoach.com/dsgen/generator/1.0"
      nsPrefix="dsgenerator">
    <eClassifiers xsi:type="ecore:EClass" name="EObjectGenerator">
      <eOperations name="getInstances" eType="#//generator/EObjectCollection">
        <eParameters name="cl" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetDSGenClass" eType="#//DSGenClass"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../com.opcoach.generator.model/model/generator.ecore#//ValueGenerator">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChildrenGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxChildrenNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="50"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../com.opcoach.generator.model/model/generator.ecore#//ValueGenerator">
        <eTypeArguments eClassifier="#//generator/EObjectCollection"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EObjectCollection" instanceTypeName="java.util.Collection&lt;org.eclipse.emf.ecore.EObject>"/>
    <eClassifiers xsi:type="ecore:EClass" name="SingleAssociationGenerator">
      <eGenericSuperTypes eClassifier="ecore:EClass ../../com.opcoach.generator.model/model/generator.ecore#//ReferenceGenerator">
        <eTypeArguments eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultipleAssociationGenerator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxAssociationNumber"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="50"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../com.opcoach.generator.model/model/generator.ecore#//ValueGenerator">
        <eTypeArguments eClassifier="#//generator/EObjectCollection"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
