/*
 * generated by Xtext
 */
package com.opcoach.datasample.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DataSampleDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DataSampleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.DataSample");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDataSampleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSampleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPackageURIAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPackageURIEStringParserRuleCall_4_0 = (RuleCall)cPackageURIAssignment_4.eContents().get(0);
		private final Keyword cSeedKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSeedAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSeedEIntParserRuleCall_6_0 = (RuleCall)cSeedAssignment_6.eContents().get(0);
		private final Keyword cLanguageKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cLanguageAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cLanguageLanguageEnumRuleCall_8_0 = (RuleCall)cLanguageAssignment_8.eContents().get(0);
		private final Assignment cEntityGeneratorsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cEntityGeneratorsEntityGeneratorParserRuleCall_9_0 = (RuleCall)cEntityGeneratorsAssignment_9.eContents().get(0);
		
		//DataSample:
		//	{DataSample}
		//	'Sample'
		//	name=EString 'for' packageURI=EString
		//	'seed' seed=EInt
		//	'language' language=Language
		//	entityGenerators+=EntityGenerator* // ("," entityGenerators+=EntityGenerator)*
		//;
		@Override public ParserRule getRule() { return rule; }

		//{DataSample} 'Sample' name=EString 'for' packageURI=EString 'seed' seed=EInt 'language' language=Language
		//entityGenerators+=EntityGenerator*
		public Group getGroup() { return cGroup; }

		//{DataSample}
		public Action getDataSampleAction_0() { return cDataSampleAction_0; }

		//'Sample'
		public Keyword getSampleKeyword_1() { return cSampleKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//'for'
		public Keyword getForKeyword_3() { return cForKeyword_3; }

		//packageURI=EString
		public Assignment getPackageURIAssignment_4() { return cPackageURIAssignment_4; }

		//EString
		public RuleCall getPackageURIEStringParserRuleCall_4_0() { return cPackageURIEStringParserRuleCall_4_0; }

		//'seed'
		public Keyword getSeedKeyword_5() { return cSeedKeyword_5; }

		//seed=EInt
		public Assignment getSeedAssignment_6() { return cSeedAssignment_6; }

		//EInt
		public RuleCall getSeedEIntParserRuleCall_6_0() { return cSeedEIntParserRuleCall_6_0; }

		//'language'
		public Keyword getLanguageKeyword_7() { return cLanguageKeyword_7; }

		//language=Language
		public Assignment getLanguageAssignment_8() { return cLanguageAssignment_8; }

		//Language
		public RuleCall getLanguageLanguageEnumRuleCall_8_0() { return cLanguageLanguageEnumRuleCall_8_0; }

		//entityGenerators+=EntityGenerator*
		public Assignment getEntityGeneratorsAssignment_9() { return cEntityGeneratorsAssignment_9; }

		//EntityGenerator
		public RuleCall getEntityGeneratorsEntityGeneratorParserRuleCall_9_0() { return cEntityGeneratorsEntityGeneratorParserRuleCall_9_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }

		//'-'? INT
		public Group getGroup() { return cGroup; }

		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EntityGeneratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.EntityGenerator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntityGeneratorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGenerateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumberEIntParserRuleCall_2_0 = (RuleCall)cNumberAssignment_2.eContents().get(0);
		private final Assignment cEntityNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEntityNameEStringParserRuleCall_3_0 = (RuleCall)cEntityNameAssignment_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cFieldGeneratorsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFieldGeneratorsFieldGeneratorParserRuleCall_5_0 = (RuleCall)cFieldGeneratorsAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EntityGenerator:
		//	{EntityGenerator}
		//	'generate' number=EInt entityName=EString
		//	'{'
		//	fieldGenerators+=FieldGenerator*
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//{EntityGenerator} 'generate' number=EInt entityName=EString '{' fieldGenerators+=FieldGenerator* '}'
		public Group getGroup() { return cGroup; }

		//{EntityGenerator}
		public Action getEntityGeneratorAction_0() { return cEntityGeneratorAction_0; }

		//'generate'
		public Keyword getGenerateKeyword_1() { return cGenerateKeyword_1; }

		//number=EInt
		public Assignment getNumberAssignment_2() { return cNumberAssignment_2; }

		//EInt
		public RuleCall getNumberEIntParserRuleCall_2_0() { return cNumberEIntParserRuleCall_2_0; }

		//entityName=EString
		public Assignment getEntityNameAssignment_3() { return cEntityNameAssignment_3; }

		//EString
		public RuleCall getEntityNameEStringParserRuleCall_3_0() { return cEntityNameEStringParserRuleCall_3_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//fieldGenerators+=FieldGenerator*
		public Assignment getFieldGeneratorsAssignment_5() { return cFieldGeneratorsAssignment_5; }

		//FieldGenerator
		public RuleCall getFieldGeneratorsFieldGeneratorParserRuleCall_5_0() { return cFieldGeneratorsFieldGeneratorParserRuleCall_5_0; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class FieldGeneratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.FieldGenerator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldGeneratorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cForFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFieldNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFieldNameEStringParserRuleCall_2_0 = (RuleCall)cFieldNameAssignment_2.eContents().get(0);
		private final Keyword cUseKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cGeneratorNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGeneratorNameEStringParserRuleCall_4_0 = (RuleCall)cGeneratorNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cWithErrorRateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cErrorRateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cErrorRateEIntParserRuleCall_5_1_0 = (RuleCall)cErrorRateAssignment_5_1.eContents().get(0);
		private final Keyword cGeneratedWithKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cErrorGeneratorNameAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cErrorGeneratorNameEStringParserRuleCall_5_3_0 = (RuleCall)cErrorGeneratorNameAssignment_5_3.eContents().get(0);
		
		//FieldGenerator:
		//	{FieldGenerator}
		//	'forField' fieldName=EString 'use' generatorName=EString ('withErrorRate=' errorRate=EInt 'generatedWith'
		//	errorGeneratorName=EString)?;
		@Override public ParserRule getRule() { return rule; }

		//{FieldGenerator} 'forField' fieldName=EString 'use' generatorName=EString ('withErrorRate=' errorRate=EInt
		//'generatedWith' errorGeneratorName=EString)?
		public Group getGroup() { return cGroup; }

		//{FieldGenerator}
		public Action getFieldGeneratorAction_0() { return cFieldGeneratorAction_0; }

		//'forField'
		public Keyword getForFieldKeyword_1() { return cForFieldKeyword_1; }

		//fieldName=EString
		public Assignment getFieldNameAssignment_2() { return cFieldNameAssignment_2; }

		//EString
		public RuleCall getFieldNameEStringParserRuleCall_2_0() { return cFieldNameEStringParserRuleCall_2_0; }

		//'use'
		public Keyword getUseKeyword_3() { return cUseKeyword_3; }

		//generatorName=EString
		public Assignment getGeneratorNameAssignment_4() { return cGeneratorNameAssignment_4; }

		//EString
		public RuleCall getGeneratorNameEStringParserRuleCall_4_0() { return cGeneratorNameEStringParserRuleCall_4_0; }

		//('withErrorRate=' errorRate=EInt 'generatedWith' errorGeneratorName=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//'withErrorRate='
		public Keyword getWithErrorRateKeyword_5_0() { return cWithErrorRateKeyword_5_0; }

		//errorRate=EInt
		public Assignment getErrorRateAssignment_5_1() { return cErrorRateAssignment_5_1; }

		//EInt
		public RuleCall getErrorRateEIntParserRuleCall_5_1_0() { return cErrorRateEIntParserRuleCall_5_1_0; }

		//'generatedWith'
		public Keyword getGeneratedWithKeyword_5_2() { return cGeneratedWithKeyword_5_2; }

		//errorGeneratorName=EString
		public Assignment getErrorGeneratorNameAssignment_5_3() { return cErrorGeneratorNameAssignment_5_3; }

		//EString
		public RuleCall getErrorGeneratorNameEStringParserRuleCall_5_3_0() { return cErrorGeneratorNameEStringParserRuleCall_5_3_0; }
	}
	
	
	public class LanguageElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.Language");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFrEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFrFrKeyword_0_0 = (Keyword)cFrEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEnEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEnEnKeyword_1_0 = (Keyword)cEnEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDeDeKeyword_2_0 = (Keyword)cDeEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEsEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEsEsKeyword_3_0 = (Keyword)cEsEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cItEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cItItKeyword_4_0 = (Keyword)cItEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Language:
		//	fr | en | de | es | it;
		public EnumRule getRule() { return rule; }

		//fr | en | de | es | it
		public Alternatives getAlternatives() { return cAlternatives; }

		//fr
		public EnumLiteralDeclaration getFrEnumLiteralDeclaration_0() { return cFrEnumLiteralDeclaration_0; }

		//'fr'
		public Keyword getFrFrKeyword_0_0() { return cFrFrKeyword_0_0; }

		//en
		public EnumLiteralDeclaration getEnEnumLiteralDeclaration_1() { return cEnEnumLiteralDeclaration_1; }

		//'en'
		public Keyword getEnEnKeyword_1_0() { return cEnEnKeyword_1_0; }

		//de
		public EnumLiteralDeclaration getDeEnumLiteralDeclaration_2() { return cDeEnumLiteralDeclaration_2; }

		//'de'
		public Keyword getDeDeKeyword_2_0() { return cDeDeKeyword_2_0; }

		//es
		public EnumLiteralDeclaration getEsEnumLiteralDeclaration_3() { return cEsEnumLiteralDeclaration_3; }

		//'es'
		public Keyword getEsEsKeyword_3_0() { return cEsEsKeyword_3_0; }

		//it
		public EnumLiteralDeclaration getItEnumLiteralDeclaration_4() { return cItEnumLiteralDeclaration_4; }

		//'it'
		public Keyword getItItKeyword_4_0() { return cItItKeyword_4_0; }
	}
	
	private final DataSampleElements pDataSample;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final LanguageElements eLanguage;
	private final EntityGeneratorElements pEntityGenerator;
	private final FieldGeneratorElements pFieldGenerator;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DataSampleDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDataSample = new DataSampleElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.eLanguage = new LanguageElements();
		this.pEntityGenerator = new EntityGeneratorElements();
		this.pFieldGenerator = new FieldGeneratorElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.opcoach.datasample.xtext.DataSampleDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DataSample:
	//	{DataSample}
	//	'Sample'
	//	name=EString 'for' packageURI=EString
	//	'seed' seed=EInt
	//	'language' language=Language
	//	entityGenerators+=EntityGenerator* // ("," entityGenerators+=EntityGenerator)*
	//;
	public DataSampleElements getDataSampleAccess() {
		return pDataSample;
	}
	
	public ParserRule getDataSampleRule() {
		return getDataSampleAccess().getRule();
	}

	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//enum Language:
	//	fr | en | de | es | it;
	public LanguageElements getLanguageAccess() {
		return eLanguage;
	}
	
	public EnumRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}

	//EntityGenerator:
	//	{EntityGenerator}
	//	'generate' number=EInt entityName=EString
	//	'{'
	//	fieldGenerators+=FieldGenerator*
	//	'}';
	public EntityGeneratorElements getEntityGeneratorAccess() {
		return pEntityGenerator;
	}
	
	public ParserRule getEntityGeneratorRule() {
		return getEntityGeneratorAccess().getRule();
	}

	//FieldGenerator:
	//	{FieldGenerator}
	//	'forField' fieldName=EString 'use' generatorName=EString ('withErrorRate=' errorRate=EInt 'generatedWith'
	//	errorGeneratorName=EString)?;
	public FieldGeneratorElements getFieldGeneratorAccess() {
		return pFieldGenerator;
	}
	
	public ParserRule getFieldGeneratorRule() {
		return getFieldGeneratorAccess().getRule();
	}

	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
