/*
 * generated by Xtext
 */
package com.opcoach.datasample.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DataSampleDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DataSampleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.DataSample");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDataSampleAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSampleKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cForKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPackageURIAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPackageURIEStringParserRuleCall_4_0 = (RuleCall)cPackageURIAssignment_4.eContents().get(0);
		private final Keyword cGenerateRootObjectKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRootEntityNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRootEntityNameEStringParserRuleCall_6_0 = (RuleCall)cRootEntityNameAssignment_6.eContents().get(0);
		private final Keyword cSeedKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSeedAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSeedEIntParserRuleCall_8_0 = (RuleCall)cSeedAssignment_8.eContents().get(0);
		private final Keyword cLanguageKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cLanguageAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cLanguageLanguageEnumRuleCall_10_0 = (RuleCall)cLanguageAssignment_10.eContents().get(0);
		private final Assignment cEntityGeneratorsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cEntityGeneratorsEntityGeneratorParserRuleCall_11_0 = (RuleCall)cEntityGeneratorsAssignment_11.eContents().get(0);
		
		//DataSample:
		//	{DataSample}
		//	'Sample'
		//	name=EString 'for' packageURI=EString
		//	'generateRootObject' rootEntityName=EString
		//	'seed' seed=EInt
		//	'language' language=Language
		//	entityGenerators+=EntityGenerator* // ("," entityGenerators+=EntityGenerator)*
		//;
		@Override public ParserRule getRule() { return rule; }

		//{DataSample} 'Sample' name=EString 'for' packageURI=EString 'generateRootObject' rootEntityName=EString 'seed' seed=EInt
		//'language' language=Language entityGenerators+=EntityGenerator*
		public Group getGroup() { return cGroup; }

		//{DataSample}
		public Action getDataSampleAction_0() { return cDataSampleAction_0; }

		//'Sample'
		public Keyword getSampleKeyword_1() { return cSampleKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//'for'
		public Keyword getForKeyword_3() { return cForKeyword_3; }

		//packageURI=EString
		public Assignment getPackageURIAssignment_4() { return cPackageURIAssignment_4; }

		//EString
		public RuleCall getPackageURIEStringParserRuleCall_4_0() { return cPackageURIEStringParserRuleCall_4_0; }

		//'generateRootObject'
		public Keyword getGenerateRootObjectKeyword_5() { return cGenerateRootObjectKeyword_5; }

		//rootEntityName=EString
		public Assignment getRootEntityNameAssignment_6() { return cRootEntityNameAssignment_6; }

		//EString
		public RuleCall getRootEntityNameEStringParserRuleCall_6_0() { return cRootEntityNameEStringParserRuleCall_6_0; }

		//'seed'
		public Keyword getSeedKeyword_7() { return cSeedKeyword_7; }

		//seed=EInt
		public Assignment getSeedAssignment_8() { return cSeedAssignment_8; }

		//EInt
		public RuleCall getSeedEIntParserRuleCall_8_0() { return cSeedEIntParserRuleCall_8_0; }

		//'language'
		public Keyword getLanguageKeyword_9() { return cLanguageKeyword_9; }

		//language=Language
		public Assignment getLanguageAssignment_10() { return cLanguageAssignment_10; }

		//Language
		public RuleCall getLanguageLanguageEnumRuleCall_10_0() { return cLanguageLanguageEnumRuleCall_10_0; }

		//entityGenerators+=EntityGenerator*
		public Assignment getEntityGeneratorsAssignment_11() { return cEntityGeneratorsAssignment_11; }

		//EntityGenerator
		public RuleCall getEntityGeneratorsEntityGeneratorParserRuleCall_11_0() { return cEntityGeneratorsEntityGeneratorParserRuleCall_11_0; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }

		//'-'? INT
		public Group getGroup() { return cGroup; }

		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class EntityGeneratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.EntityGenerator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEntityGeneratorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGenerateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumberAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumberEIntParserRuleCall_2_0 = (RuleCall)cNumberAssignment_2.eContents().get(0);
		private final Keyword cInstancesOfKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cEntityNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cEntityNameEStringParserRuleCall_4_0 = (RuleCall)cEntityNameAssignment_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFieldGeneratorsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFieldGeneratorsFieldGeneratorParserRuleCall_6_0 = (RuleCall)cFieldGeneratorsAssignment_6.eContents().get(0);
		private final Assignment cChildGeneratorsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cChildGeneratorsEntityGeneratorParserRuleCall_7_0 = (RuleCall)cChildGeneratorsAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//EntityGenerator:
		//	{EntityGenerator}
		//	'generate' number=EInt 'instancesOf' entityName=EString
		//	'{'
		//	fieldGenerators+=FieldGenerator*
		//	childGenerators+=EntityGenerator*
		//	'}';
		@Override public ParserRule getRule() { return rule; }

		//{EntityGenerator} 'generate' number=EInt 'instancesOf' entityName=EString '{' fieldGenerators+=FieldGenerator*
		//childGenerators+=EntityGenerator* '}'
		public Group getGroup() { return cGroup; }

		//{EntityGenerator}
		public Action getEntityGeneratorAction_0() { return cEntityGeneratorAction_0; }

		//'generate'
		public Keyword getGenerateKeyword_1() { return cGenerateKeyword_1; }

		//number=EInt
		public Assignment getNumberAssignment_2() { return cNumberAssignment_2; }

		//EInt
		public RuleCall getNumberEIntParserRuleCall_2_0() { return cNumberEIntParserRuleCall_2_0; }

		//'instancesOf'
		public Keyword getInstancesOfKeyword_3() { return cInstancesOfKeyword_3; }

		//entityName=EString
		public Assignment getEntityNameAssignment_4() { return cEntityNameAssignment_4; }

		//EString
		public RuleCall getEntityNameEStringParserRuleCall_4_0() { return cEntityNameEStringParserRuleCall_4_0; }

		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//fieldGenerators+=FieldGenerator*
		public Assignment getFieldGeneratorsAssignment_6() { return cFieldGeneratorsAssignment_6; }

		//FieldGenerator
		public RuleCall getFieldGeneratorsFieldGeneratorParserRuleCall_6_0() { return cFieldGeneratorsFieldGeneratorParserRuleCall_6_0; }

		//childGenerators+=EntityGenerator*
		public Assignment getChildGeneratorsAssignment_7() { return cChildGeneratorsAssignment_7; }

		//EntityGenerator
		public RuleCall getChildGeneratorsEntityGeneratorParserRuleCall_7_0() { return cChildGeneratorsEntityGeneratorParserRuleCall_7_0; }

		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}

	public class FieldGeneratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.FieldGenerator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFieldGeneratorAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cForFieldKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFieldNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFieldNameEStringParserRuleCall_2_0 = (RuleCall)cFieldNameAssignment_2.eContents().get(0);
		private final Keyword cUseKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cGeneratorNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGeneratorNameEStringParserRuleCall_4_0 = (RuleCall)cGeneratorNameAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftParenthesisKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cParametersAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_5_1_0 = (RuleCall)cParametersAssignment_5_1.eContents().get(0);
		private final Group cGroup_5_2 = (Group)cGroup_5.eContents().get(2);
		private final Keyword cCommaKeyword_5_2_0 = (Keyword)cGroup_5_2.eContents().get(0);
		private final Assignment cParametersAssignment_5_2_1 = (Assignment)cGroup_5_2.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_5_2_1_0 = (RuleCall)cParametersAssignment_5_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWithErrorRateKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cErrorRateAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cErrorRateEIntParserRuleCall_6_1_0 = (RuleCall)cErrorRateAssignment_6_1.eContents().get(0);
		private final Keyword cGeneratedWithKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cErrorGeneratorNameAssignment_6_3 = (Assignment)cGroup_6.eContents().get(3);
		private final RuleCall cErrorGeneratorNameEStringParserRuleCall_6_3_0 = (RuleCall)cErrorGeneratorNameAssignment_6_3.eContents().get(0);
		
		//FieldGenerator:
		//	{FieldGenerator}
		//	'forField' fieldName=EString 'use' generatorName=EString ('(' parameters+=Parameter (',' parameters+=Parameter)* ')')?
		//	('withErrorRate=' errorRate=EInt 'generatedWith'
		//	errorGeneratorName=EString)?;
		@Override public ParserRule getRule() { return rule; }

		//{FieldGenerator} 'forField' fieldName=EString 'use' generatorName=EString ('(' parameters+=Parameter (','
		//parameters+=Parameter)* ')')? ('withErrorRate=' errorRate=EInt 'generatedWith' errorGeneratorName=EString)?
		public Group getGroup() { return cGroup; }

		//{FieldGenerator}
		public Action getFieldGeneratorAction_0() { return cFieldGeneratorAction_0; }

		//'forField'
		public Keyword getForFieldKeyword_1() { return cForFieldKeyword_1; }

		//fieldName=EString
		public Assignment getFieldNameAssignment_2() { return cFieldNameAssignment_2; }

		//EString
		public RuleCall getFieldNameEStringParserRuleCall_2_0() { return cFieldNameEStringParserRuleCall_2_0; }

		//'use'
		public Keyword getUseKeyword_3() { return cUseKeyword_3; }

		//generatorName=EString
		public Assignment getGeneratorNameAssignment_4() { return cGeneratorNameAssignment_4; }

		//EString
		public RuleCall getGeneratorNameEStringParserRuleCall_4_0() { return cGeneratorNameEStringParserRuleCall_4_0; }

		//('(' parameters+=Parameter (',' parameters+=Parameter)* ')')?
		public Group getGroup_5() { return cGroup_5; }

		//'('
		public Keyword getLeftParenthesisKeyword_5_0() { return cLeftParenthesisKeyword_5_0; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_5_1() { return cParametersAssignment_5_1; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_5_1_0() { return cParametersParameterParserRuleCall_5_1_0; }

		//(',' parameters+=Parameter)*
		public Group getGroup_5_2() { return cGroup_5_2; }

		//','
		public Keyword getCommaKeyword_5_2_0() { return cCommaKeyword_5_2_0; }

		//parameters+=Parameter
		public Assignment getParametersAssignment_5_2_1() { return cParametersAssignment_5_2_1; }

		//Parameter
		public RuleCall getParametersParameterParserRuleCall_5_2_1_0() { return cParametersParameterParserRuleCall_5_2_1_0; }

		//')'
		public Keyword getRightParenthesisKeyword_5_3() { return cRightParenthesisKeyword_5_3; }

		//('withErrorRate=' errorRate=EInt 'generatedWith' errorGeneratorName=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//'withErrorRate='
		public Keyword getWithErrorRateKeyword_6_0() { return cWithErrorRateKeyword_6_0; }

		//errorRate=EInt
		public Assignment getErrorRateAssignment_6_1() { return cErrorRateAssignment_6_1; }

		//EInt
		public RuleCall getErrorRateEIntParserRuleCall_6_1_0() { return cErrorRateEIntParserRuleCall_6_1_0; }

		//'generatedWith'
		public Keyword getGeneratedWithKeyword_6_2() { return cGeneratedWithKeyword_6_2; }

		//errorGeneratorName=EString
		public Assignment getErrorGeneratorNameAssignment_6_3() { return cErrorGeneratorNameAssignment_6_3; }

		//EString
		public RuleCall getErrorGeneratorNameEStringParserRuleCall_6_3_0() { return cErrorGeneratorNameEStringParserRuleCall_6_3_0; }
	}

	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.Parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueEStringParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//Parameter:
		//	name=ID '=' value=EString;
		@Override public ParserRule getRule() { return rule; }

		//name=ID '=' value=EString
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//'='
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=EString
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//EString
		public RuleCall getValueEStringParserRuleCall_2_0() { return cValueEStringParserRuleCall_2_0; }
	}
	
	
	public class LanguageElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "com.opcoach.datasample.xtext.DataSampleDSL.Language");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFrEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFrFrKeyword_0_0 = (Keyword)cFrEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEnEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEnEnKeyword_1_0 = (Keyword)cEnEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDeDeKeyword_2_0 = (Keyword)cDeEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cEsEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cEsEsKeyword_3_0 = (Keyword)cEsEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cItEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cItItKeyword_4_0 = (Keyword)cItEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Language:
		//	fr | en | de | es | it;
		public EnumRule getRule() { return rule; }

		//fr | en | de | es | it
		public Alternatives getAlternatives() { return cAlternatives; }

		//fr
		public EnumLiteralDeclaration getFrEnumLiteralDeclaration_0() { return cFrEnumLiteralDeclaration_0; }

		//'fr'
		public Keyword getFrFrKeyword_0_0() { return cFrFrKeyword_0_0; }

		//en
		public EnumLiteralDeclaration getEnEnumLiteralDeclaration_1() { return cEnEnumLiteralDeclaration_1; }

		//'en'
		public Keyword getEnEnKeyword_1_0() { return cEnEnKeyword_1_0; }

		//de
		public EnumLiteralDeclaration getDeEnumLiteralDeclaration_2() { return cDeEnumLiteralDeclaration_2; }

		//'de'
		public Keyword getDeDeKeyword_2_0() { return cDeDeKeyword_2_0; }

		//es
		public EnumLiteralDeclaration getEsEnumLiteralDeclaration_3() { return cEsEnumLiteralDeclaration_3; }

		//'es'
		public Keyword getEsEsKeyword_3_0() { return cEsEsKeyword_3_0; }

		//it
		public EnumLiteralDeclaration getItEnumLiteralDeclaration_4() { return cItEnumLiteralDeclaration_4; }

		//'it'
		public Keyword getItItKeyword_4_0() { return cItItKeyword_4_0; }
	}
	
	private final DataSampleElements pDataSample;
	private final EStringElements pEString;
	private final EIntElements pEInt;
	private final LanguageElements eLanguage;
	private final EntityGeneratorElements pEntityGenerator;
	private final FieldGeneratorElements pFieldGenerator;
	private final ParameterElements pParameter;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DataSampleDSLGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDataSample = new DataSampleElements();
		this.pEString = new EStringElements();
		this.pEInt = new EIntElements();
		this.eLanguage = new LanguageElements();
		this.pEntityGenerator = new EntityGeneratorElements();
		this.pFieldGenerator = new FieldGeneratorElements();
		this.pParameter = new ParameterElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.opcoach.datasample.xtext.DataSampleDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DataSample:
	//	{DataSample}
	//	'Sample'
	//	name=EString 'for' packageURI=EString
	//	'generateRootObject' rootEntityName=EString
	//	'seed' seed=EInt
	//	'language' language=Language
	//	entityGenerators+=EntityGenerator* // ("," entityGenerators+=EntityGenerator)*
	//;
	public DataSampleElements getDataSampleAccess() {
		return pDataSample;
	}
	
	public ParserRule getDataSampleRule() {
		return getDataSampleAccess().getRule();
	}

	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//enum Language:
	//	fr | en | de | es | it;
	public LanguageElements getLanguageAccess() {
		return eLanguage;
	}
	
	public EnumRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}

	//EntityGenerator:
	//	{EntityGenerator}
	//	'generate' number=EInt 'instancesOf' entityName=EString
	//	'{'
	//	fieldGenerators+=FieldGenerator*
	//	childGenerators+=EntityGenerator*
	//	'}';
	public EntityGeneratorElements getEntityGeneratorAccess() {
		return pEntityGenerator;
	}
	
	public ParserRule getEntityGeneratorRule() {
		return getEntityGeneratorAccess().getRule();
	}

	//FieldGenerator:
	//	{FieldGenerator}
	//	'forField' fieldName=EString 'use' generatorName=EString ('(' parameters+=Parameter (',' parameters+=Parameter)* ')')?
	//	('withErrorRate=' errorRate=EInt 'generatedWith'
	//	errorGeneratorName=EString)?;
	public FieldGeneratorElements getFieldGeneratorAccess() {
		return pFieldGenerator;
	}
	
	public ParserRule getFieldGeneratorRule() {
		return getFieldGeneratorAccess().getRule();
	}

	//Parameter:
	//	name=ID '=' value=EString;
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}

	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
