/*
* generated by Xtext
*/
package com.opcoach.dsgen.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DSGenDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/opcoach/dsgen/xtext/parser/antlr/internal/InternalDSGenDSL.tokens");
	}
}
