/*
 * generated by Xtext
 */
package com.opcoach.datasample.xtext.validation

import com.opcoach.datasample.ChildrenGenerator
import com.opcoach.datasample.MDatasamplePackage
import org.eclipse.xtext.validation.Check

//import org.eclipse.xtext.validation.Check
/**
 * Custom validation rules. 
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class DataSampleDSLValidator extends AbstractDataSampleDSLValidator {

	public static val GENERATOR_NB_GREATER_THAN_UPPER_BOUND = 'generatorNumberGreaterThanUpperBound'

	@Check
	def checkGeneratorNumber(ChildrenGenerator cg) {
		val upper = cg.EReference.upperBound
		if(upper == -1) return;

		if (cg.number > upper) {
			error(
				"The number of generated children (" + cg.number + ") is greater than upper bound of the eReference " +
					cg.EReference.name, MDatasamplePackage.Literals.FIELD_GENERATOR__NUMBER,
				GENERATOR_NB_GREATER_THAN_UPPER_BOUND)
		}
	}
}
