/*
 * generated by Xtext
 */
package com.opcoach.datasample.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DataSampleDSLUiModule extends com.opcoach.datasample.xtext.ui.AbstractDataSampleDSLUiModule {
	public DataSampleDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
