/*
 * generated by Xtext
 */
package com.opcoach.datasample.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.opcoach.datasample.xtext.ui.internal.DataSampleDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DataSampleDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DataSampleDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DataSampleDSLActivator.getInstance().getInjector(DataSampleDSLActivator.COM_OPCOACH_DATASAMPLE_XTEXT_DATASAMPLEDSL);
	}
	
}
