/*
 * generated by Xtext
 */
package com.opcoach.dsgen.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSGenDSLRuntimeModule extends com.opcoach.dsgen.xtext.AbstractDSGenDSLRuntimeModule {

}
