/*
* generated by Xtext
*/
package com.opcoach.dsgen.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DSGenDSLStandaloneSetup extends DSGenDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new DSGenDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

